autoglsa: switch Relationship column assignments to appends
This prevents a few type-clashing issues on assignment:

glsamaker/autoglsa.py:253: error: Incompatible types in assignment (expression has type "list[Any]", variable has type "RelationshipProperty[Any]")  [assignment]
glsamaker/autoglsa.py:260: error: Incompatible types in assignment (expression has type "list[Any]", variable has type "RelationshipProperty[Any]")  [assignment]
glsamaker/autoglsa.py:270: error: Incompatible types in assignment (expression has type "list[Affected]", variable has type "RelationshipProperty[Any]")  [assignment]

Signed-off-by: John Helmert III <ajak@gentoo.org>